/**
 * Emits gauntlet/evidence/audio-graph.json and then judges it with the REAL
 * rubric.
 *
 * Two things happen here and they are deliberately in one file:
 *
 *   1. The artifact is DERIVED. `buildAudioEvidence` builds the graph on a
 *      recording context, walks the route, plays three thousand sound effects,
 *      measures the duck and reads the transport back. Nothing is typed in.
 *   2. The artifact is JUDGED by the actual rubric functions imported from
 *      tests/gauntlet/rubric.mjs - not by a copy of their thresholds. If a
 *      threshold in the rubric moves, this test moves with it, and an artifact
 *      that would not turn A-21.1..A-21.5 green fails here first.
 *
 * Writing the file from a test is the point: it is regenerated by `npm test`,
 * so it can never drift from the code it describes (D85).
 *
 * AND WHAT THIS FILE ALONE CANNOT SETTLE. The graph it measures is built HERE,
 * on a null context, by a unit test. That graph is correct and it was, for a
 * while, connected to nothing: `createAudioSystem()` had no caller outside its
 * own test and the game was silent while all five items read green
 * (audit.md 1.2). So the rubric now demands a SECOND artifact,
 * `audio-wiring.json`, produced by `tests/e2e/audio-wiring.spec.ts` against a
 * real browser boot. The last describe block below is the guard on that: it
 * feeds the real rubric functions a graph artifact with no wiring artifact, and
 * then with a wiring artifact shaped like a disconnected game, and requires
 * that neither passes. If someone later loosens the items back to "built", this
 * test fails before the game goes quiet again.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
// tests/gauntlet/rubric.mjs is plain JS - it is the gauntlet's own contract and
// is read by node, not tsc. Importing it here is deliberate: judging the
// artifact with a COPY of the rubric's thresholds would let the two drift.
// @ts-expect-error - untyped .mjs, shaped below.
import { RUBRIC as RUBRIC_UNTYPED } from "../../gauntlet/rubric.mjs";
import { buildAudioEvidence, countingFetchProbe } from "../../../src/game/audio/evidence.js";
import { STOP_IDS } from "../../../src/engine/types.js";
import { SFX_EVENTS, MIN_VARIANTS_PER_EVENT } from "../../../src/game/audio/sfx.js";
import { MUSIC_LAYER_COUNT } from "../../../src/game/audio/music.js";
import { fakeVoiceEnvironment, shippingVoiceEnvironment } from "./fakes.js";

interface RubricItem {
  readonly id: string;
  readonly kind: string;
  run(context: { repo: string; evidence: unknown }): Promise<{ status: string; detail: string }>;
}
const RUBRIC = RUBRIC_UNTYPED as RubricItem[];

const REPO = process.cwd();
const EVIDENCE_DIR = join(REPO, "gauntlet/evidence");
const ARTIFACT = "audio-graph.json";
const AUDIO_SRC = join(REPO, "src/game/audio");

/** The one rubric item D98 collided with. See C16 and the test that pins it. */
const COLLIDING_ITEM = "A-21.5";

/**
 * The static half of the AC-21.5 network claim. The runtime probe proves the
 * voice path never calls the fetch it was handed; this proves no file reaches
 * around it for a global one. The count is added to the probe's, so a source
 * file that named `fetch` could not produce a zero in the artifact.
 */
function staticNetworkReferences(): number {
  const banned = [/\bfetch\s*\(/g, /XMLHttpRequest/g, /\bWebSocket\b/g, /https?:\/\//g];
  let hits = 0;
  for (const file of readdirSync(AUDIO_SRC).filter((f) => f.endsWith(".ts"))) {
    const source = readFileSync(join(AUDIO_SRC, file), "utf8")
      .replace(/\/\*[\s\S]*?\*\//g, " ")
      .replace(/(^|[^:])\/\/.*$/gm, "$1");
    for (const pattern of banned) hits += (source.match(pattern) ?? []).length;
  }
  return hits;
}

/**
 * UR-46: the artifact is built on the env a CHILD gets, not the one a test
 * opts into. See `shippingVoiceEnvironment`. This single substitution is what
 * turns `voiceTransport` from "webspeech" into the truth, and it is what makes
 * rubric item A-21.5 go red - see the documented collision below.
 */
const { env } = shippingVoiceEnvironment();
const evidenceData = buildAudioEvidence(env, {
  rotationsPerEvent: 300,
  staticNetworkReferences: staticNetworkReferences(),
});

describe("the audio evidence artifact is derived from the real graph", () => {
  it("AC-21.1: reports the seven ambient beds the graph actually built", () => {
    expect(evidenceData.ambientBeds).toEqual([...STOP_IDS]);
    expect(evidenceData.ambientBeds.length).toBe(7);
  });

  it("AC-21.1: reports a crossfade observed on every transition", () => {
    expect(evidenceData.crossfade).toBe(true);
  });

  it("AC-21.2: reports the music layer gains the bus created", () => {
    expect(evidenceData.musicLayers).toBe(MUSIC_LAYER_COUNT);
    expect(evidenceData.musicLayers).toBeGreaterThanOrEqual(3);
  });

  it("AC-21.3: reports distinct variants OBSERVED over 300 plays per event", () => {
    expect(Object.keys(evidenceData.sfxVariants).sort()).toEqual([...SFX_EVENTS].sort());
    for (const event of SFX_EVENTS) {
      expect(evidenceData.sfxVariants[event], event).toBeGreaterThanOrEqual(
        MIN_VARIANTS_PER_EVENT,
      );
    }
  });

  it("AC-21.3: reports no consecutive repeat, scanned from the play history", () => {
    expect(evidenceData.noConsecutiveRepeat).toBe(true);
  });

  it("AC-21.4: reports the duck it MEASURED, at 6 dB or deeper", () => {
    expect(evidenceData.duckDb).toBeLessThanOrEqual(-6);
    expect(Number.isFinite(evidenceData.duckDb)).toBe(true);
  });

  /**
   * UR-46. THIS EXPECTED "webspeech" AND THAT WAS THE DEFECT, not the fix.
   *
   * The artifact was built on `fakeVoiceEnvironment`, which sets
   * `allowSystemVoice: true` and documents itself as the "this session opted in"
   * fixture. Under D98 the platform voice is OFF unless the URL asks for it, so
   * no child is ever on that path - and the evidence for AC-21.5 was describing
   * a session nobody has.
   *
   * This is not a threshold moved to fit a new number. `runtimeTtsNetworkCalls`
   * - the half of AC-21.5 that is actually about network TTS - is unchanged and
   * still zero. What changed is that the transport field now says what a player
   * gets.
   */
  it("AC-21.5: reports the transport a CHILD gets, and zero TTS calls", () => {
    expect(evidenceData.voiceTransport).toBe("silent");
    expect(evidenceData.runtimeTtsNetworkCalls).toBe(0);
  });

  it("carries EXACTLY the keys tests/gauntlet/rubric.mjs reads", () => {
    expect(Object.keys(evidenceData).sort()).toEqual(
      [
        "ambientBeds",
        "crossfade",
        "duckDb",
        "musicLayers",
        "noConsecutiveRepeat",
        "runtimeTtsNetworkCalls",
        "sfxVariants",
        "voiceTransport",
      ].sort(),
    );
  });

  it("is reproducible: a second run of the same graph reports the same thing", () => {
    const again = buildAudioEvidence(shippingVoiceEnvironment().env, {
      rotationsPerEvent: 300,
      staticNetworkReferences: staticNetworkReferences(),
    });
    expect(again).toEqual(evidenceData);
  });

  it("the fetch probe really does count, so the zero means something", () => {
    const probe = countingFetchProbe();
    expect(probe.calls).toBe(0);
    probe("https://example.invalid/tts", { method: "POST" });
    probe();
    expect(probe.calls).toBe(2);
  });

  it("reports zero TTS calls even when no probe was injected at all", () => {
    const { speech, scheduler } = fakeVoiceEnvironment();
    const withoutProbe = buildAudioEvidence(
      {
        speech,
        platform: "mac",
        lang: "en-US",
        schedule: scheduler.schedule,
        // D98: the platform voice is opt-in now. This test is about the fetch
        // probe being absent, so it keeps the speech path it was written for.
        allowSystemVoice: true,
      },
      { rotationsPerEvent: 12 },
    );
    expect(withoutProbe.runtimeTtsNetworkCalls).toBe(0);
    expect(withoutProbe.voiceTransport).toBe("webspeech");
  });

  it("counts a network reference if one is ever added to the audio source", () => {
    // The zero is load-bearing, so prove it can be non-zero.
    const poisoned = buildAudioEvidence(fakeVoiceEnvironment().env, {
      rotationsPerEvent: 12,
      staticNetworkReferences: 3,
    });
    expect(poisoned.runtimeTtsNetworkCalls).toBe(3);
  });
});

describe("D85: the artifact is written and turns the audio rubric green", () => {
  it("writes gauntlet/evidence/audio-graph.json", () => {
    if (!existsSync(EVIDENCE_DIR)) mkdirSync(EVIDENCE_DIR, { recursive: true });
    writeFileSync(join(EVIDENCE_DIR, ARTIFACT), `${JSON.stringify(evidenceData, null, 2)}\n`, "utf8");
    expect(existsSync(join(EVIDENCE_DIR, ARTIFACT))).toBe(true);
    const roundTripped = JSON.parse(readFileSync(join(EVIDENCE_DIR, ARTIFACT), "utf8"));
    expect(roundTripped).toEqual(evidenceData);
  });

  it("A-21.1 .. A-21.4 pass once BOTH the graph and the wiring are evidenced", async () => {
    const results = await runAudioItems(
      { [ARTIFACT]: evidenceData, [WIRING]: connectedWiring() },
    );
    for (const [id, result] of results) {
      if (id === COLLIDING_ITEM) continue;
      expect(`${id}: ${result.status} - ${result.detail}`).toBe(`${id}: pass - ${result.detail}`);
    }
    expect([...results.keys()]).toEqual(
      expect.arrayContaining(["A-21.1", "A-21.2", "A-21.3", "A-21.4", "A-21.5"]),
    );
  });

  /**
   * A-21.5 IS RED, ON PURPOSE, AND THIS IS THE RECORD OF WHY (C16).
   *
   * The rubric item asserts `voiceTransport === "webspeech"`, sourced to D88.
   * D98 superseded D88 - the platform voice is off unless the URL asks for it -
   * so the shipping build's transport is `silent` and the item cannot pass on an
   * honest artifact. It passed until now only because the emitter was built on
   * the opt-in fixture.
   *
   * NOTHING HERE MAKES IT PASS. `tests/gauntlet/rubric.mjs` is untouched: the
   * decision log outranks the rubric (CLAUDE.md precedence 1 over 3) and
   * rewriting the item's expectation to match the new number is re-baselining,
   * which nobody on this project may do. The gauntlet run reports A-21.5 red,
   * which is the truth and is where the verdict belongs.
   *
   * This test pins the collision so it cannot be forgotten, and it FAILS THE DAY
   * A-21.5 GOES GREEN - which forces whoever resolves C16 to come back here and
   * delete it deliberately rather than letting the red quietly heal.
   */
  it("C16: A-21.5 is red because D98 retired the transport D88 asked for", async () => {
    const results = await runAudioItems(
      { [ARTIFACT]: evidenceData, [WIRING]: connectedWiring() },
    );
    const item = results.get(COLLIDING_ITEM);
    expect(item?.status, "C16 is resolved - delete this test and unskip A-21.5").toBe("fail");
    // And it is red for THIS reason, not some other regression that happens to
    // land on the same item.
    expect(evidenceData.voiceTransport).toBe("silent");
    expect(evidenceData.runtimeTtsNetworkCalls).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// The guard: "built" is not "connected" (audit.md 1.2)
// ---------------------------------------------------------------------------

describe("audit.md 1.2: no audio item may pass on a graph the game does not play", () => {
  it("every A-21 item is not-implemented when only the graph is evidenced", async () => {
    const results = await runAudioItems({ [ARTIFACT]: evidenceData });
    for (const [id, result] of results) {
      expect(`${id}: ${result.status}`).toBe(`${id}: not-implemented`);
    }
  });

  it("every A-21 item FAILS on a wiring artifact that describes a silent game", async () => {
    // The shape a disconnected build would honestly produce: the graph exists,
    // is correct, runs on the null context nothing in a browser would give it,
    // and has played nothing for anybody.
    const disconnected = connectedWiring();
    disconnected["boot"] = {
      ...(disconnected["boot"] as Record<string, unknown>),
      contextKind: "NullAudioContext",
      framesAfterASecond: 0,
      framesAdvanced: 0,
    };
    disconnected["events"] = Object.fromEntries(
      SFX_EVENTS.map((e) => [e, { count: 0, via: [] }]),
    );
    disconnected["ambient"] = { stops: [], crossfades: 0, crossfadedOnSceneTransition: false };
    disconnected["music"] = { drivenBy: "table", hudSamples: 0, indicesObserved: [0] };
    disconnected["flightCue"] = {
      sfxPlaysBefore: 0,
      sfxPlaysAfter: 0,
      keystrokeCues: 0,
      keystrokePlays: 0,
      scheduled: [],
    };
    disconnected["uiNav"] = { audible: false, masterRmsPeak: 0 };
    disconnected["settings"] = {
      musicGainFollowedSlider: false,
      sfxGainFollowedSlider: false,
      mutedSurvived: true,
    };
    disconnected["duck"] = { measuredOnLiveGraph: false };
    disconnected["coachNote"] = { order: [], textRendered: "", displayFields: [], spoken: [] };

    const results = await runAudioItems({ [ARTIFACT]: evidenceData, [WIRING]: disconnected });
    for (const [id, result] of results) {
      expect(`${id}: ${result.status}`).toBe(`${id}: fail`);
    }
  });

  it("an item cannot pass on a wiring artifact whose plays are only tagged 'test'", async () => {
    // A tag is the provenance of a play. If the only thing that ever reached an
    // event was the harness, the event is not reachable from the game.
    const harnessOnly = connectedWiring();
    harnessOnly["events"] = Object.fromEntries(
      SFX_EVENTS.map((e) => [e, { count: 3, via: ["test:forced"] }]),
    );
    const results = await runAudioItems({ [ARTIFACT]: evidenceData, [WIRING]: harnessOnly });
    expect(results.get("A-21.3")?.status).toBe("fail");
  });
});

// ---------------------------------------------------------------------------
// helpers for the two blocks above
// ---------------------------------------------------------------------------

const WIRING = "audio-wiring.json";

/**
 * The real rubric functions, run against a directory of artifacts supplied
 * here. `repo` still points at the real repo so the items' `src/game/audio`
 * existence check is answered honestly; only the evidence is a fixture.
 */
async function runAudioItems(
  artifacts: Record<string, unknown>,
): Promise<Map<string, { status: string; detail: string }>> {
  const port = {
    has: (name: string) => Object.prototype.hasOwnProperty.call(artifacts, name),
    path: (name: string) => `gauntlet/evidence/${name}`,
    read: (name: string) => artifacts[name],
    assertNumber(name: string, key: string, predicate: (v: number) => boolean, what: string) {
      const value = (this.read(name) as Record<string, unknown>)[key];
      if (typeof value !== "number" || Number.isNaN(value)) {
        return { status: "fail", detail: `${name} has no numeric "${key}"` };
      }
      return { status: predicate(value) ? "pass" : "fail", detail: `${what}: ${key} = ${value}` };
    },
    assertShape(name: string, predicate: (d: unknown) => boolean, what: string) {
      return { status: predicate(this.read(name)) ? "pass" : "fail", detail: what };
    },
  };

  const out = new Map<string, { status: string; detail: string }>();
  for (const item of RUBRIC.filter((i) => i.kind === "audio")) {
    out.set(item.id, await item.run({ repo: REPO, evidence: port }));
  }
  return out;
}

/**
 * A wiring artifact shaped like a connected game.
 *
 * Hand-built ON PURPOSE, and it is not evidence: it is a FIXTURE for the
 * rubric's own logic. The artifact the gauntlet actually reads is written by
 * `tests/e2e/audio-wiring.spec.ts` from a real browser boot, and nothing in
 * this file can write it - `WIRING` is never passed to `writeFileSync` here.
 */
function connectedWiring(): Record<string, unknown> {
  return {
    boot: {
      onServices: true,
      onRegistry: true,
      registryKey: "kb.audio",
      contextKind: "AudioContext",
      buses: ["master", "music", "ambient", "sfx", "voice"],
      framesAdvanced: 4,
      framesAfterASecond: 62,
    },
    events: Object.fromEntries(
      SFX_EVENTS.map((e) => [e, { count: 1, via: [`flight-cue:${e}`] }]),
    ),
    ambient: { stops: ["earth", "mars"], crossfades: 1, crossfadedOnSceneTransition: true },
    music: {
      drivenBy: "FLIGHT_EVENTS.hud (liveCount, combo)",
      hudSamples: 41,
      indicesObserved: [0, 1],
    },
    flightCue: {
      sfxPlaysBefore: 0,
      sfxPlaysAfter: 18,
      keystrokeCues: 10,
      keystrokePlays: 10,
      scheduled: [{ event: "keystroke", peakGain: 0.06, via: "flight-cue:keystroke" }],
    },
    uiNav: { audible: true, masterRmsPeak: 0.111 },
    settings: {
      musicGainFollowedSlider: true,
      sfxGainFollowedSlider: true,
      mutedSurvived: true,
    },
    duck: {
      measuredOnLiveGraph: true,
      reductionDb: { music: -5.9999999, ambient: -6.0000004 },
      float32SlopDb: 1e-3,
      releasedToResting: true,
    },
    voice: {
      transport: "silent",
      browserSpeechApiPresent: false,
      spokenLines: [{ id: "preflight.line.opening", kind: "scripted" }],
    },
    coachNote: {
      order: ["text", "speech"],
      textRendered: "Nice flying.",
      displayFields: ["text"],
      spoken: [{ id: "warp.coachNote", kind: "coachNote" }],
    },
    network: {
      externalRequests: [],
      ttsNetworkCalls: 0,
      linesSpokenDuringSession: 1,
    },
    noAudioContext: {
      contextKind: "NullAudioContext",
      degradedSilently: true,
    },
  };
}
