/**
 * Emits gauntlet/evidence/audio-graph.json and then judges it with the REAL
 * rubric.
 *
 * Two things happen here and they are deliberately in one file:
 *
 *   1. The artifact is DERIVED. `buildAudioEvidence` builds the graph on a
 *      recording context, walks the route, plays three thousand sound effects,
 *      measures the duck and reads the transport back. Nothing is typed in.
 *   2. The artifact is JUDGED by the actual rubric functions imported from
 *      tests/gauntlet/rubric.mjs - not by a copy of their thresholds. If a
 *      threshold in the rubric moves, this test moves with it, and an artifact
 *      that would not turn A-21.1..A-21.5 green fails here first.
 *
 * Writing the file from a test is the point: it is regenerated by `npm test`,
 * so it can never drift from the code it describes (D85).
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
// tests/gauntlet/rubric.mjs is plain JS - it is the gauntlet's own contract and
// is read by node, not tsc. Importing it here is deliberate: judging the
// artifact with a COPY of the rubric's thresholds would let the two drift.
// @ts-expect-error - untyped .mjs, shaped below.
import { RUBRIC as RUBRIC_UNTYPED } from "../../gauntlet/rubric.mjs";
import { buildAudioEvidence, countingFetchProbe } from "../../../src/game/audio/evidence.js";
import { STOP_IDS } from "../../../src/engine/types.js";
import { SFX_EVENTS, MIN_VARIANTS_PER_EVENT } from "../../../src/game/audio/sfx.js";
import { MUSIC_LAYER_COUNT } from "../../../src/game/audio/music.js";
import { fakeVoiceEnvironment } from "./fakes.js";

interface RubricItem {
  readonly id: string;
  readonly kind: string;
  run(context: { repo: string; evidence: unknown }): Promise<{ status: string; detail: string }>;
}
const RUBRIC = RUBRIC_UNTYPED as RubricItem[];

const REPO = process.cwd();
const EVIDENCE_DIR = join(REPO, "gauntlet/evidence");
const ARTIFACT = "audio-graph.json";
const AUDIO_SRC = join(REPO, "src/game/audio");

/**
 * The static half of the AC-21.5 network claim. The runtime probe proves the
 * voice path never calls the fetch it was handed; this proves no file reaches
 * around it for a global one. The count is added to the probe's, so a source
 * file that named `fetch` could not produce a zero in the artifact.
 */
function staticNetworkReferences(): number {
  const banned = [/\bfetch\s*\(/g, /XMLHttpRequest/g, /\bWebSocket\b/g, /https?:\/\//g];
  let hits = 0;
  for (const file of readdirSync(AUDIO_SRC).filter((f) => f.endsWith(".ts"))) {
    const source = readFileSync(join(AUDIO_SRC, file), "utf8")
      .replace(/\/\*[\s\S]*?\*\//g, " ")
      .replace(/(^|[^:])\/\/.*$/gm, "$1");
    for (const pattern of banned) hits += (source.match(pattern) ?? []).length;
  }
  return hits;
}

const { env } = fakeVoiceEnvironment();
const evidenceData = buildAudioEvidence(env, {
  rotationsPerEvent: 300,
  staticNetworkReferences: staticNetworkReferences(),
});

describe("the audio evidence artifact is derived from the real graph", () => {
  it("AC-21.1: reports the seven ambient beds the graph actually built", () => {
    expect(evidenceData.ambientBeds).toEqual([...STOP_IDS]);
    expect(evidenceData.ambientBeds.length).toBe(7);
  });

  it("AC-21.1: reports a crossfade observed on every transition", () => {
    expect(evidenceData.crossfade).toBe(true);
  });

  it("AC-21.2: reports the music layer gains the bus created", () => {
    expect(evidenceData.musicLayers).toBe(MUSIC_LAYER_COUNT);
    expect(evidenceData.musicLayers).toBeGreaterThanOrEqual(3);
  });

  it("AC-21.3: reports distinct variants OBSERVED over 300 plays per event", () => {
    expect(Object.keys(evidenceData.sfxVariants).sort()).toEqual([...SFX_EVENTS].sort());
    for (const event of SFX_EVENTS) {
      expect(evidenceData.sfxVariants[event], event).toBeGreaterThanOrEqual(
        MIN_VARIANTS_PER_EVENT,
      );
    }
  });

  it("AC-21.3: reports no consecutive repeat, scanned from the play history", () => {
    expect(evidenceData.noConsecutiveRepeat).toBe(true);
  });

  it("AC-21.4: reports the duck it MEASURED, at 6 dB or deeper", () => {
    expect(evidenceData.duckDb).toBeLessThanOrEqual(-6);
    expect(Number.isFinite(evidenceData.duckDb)).toBe(true);
  });

  it("AC-21.5: reports the transport the factory returned, and zero TTS calls", () => {
    expect(evidenceData.voiceTransport).toBe("webspeech");
    expect(evidenceData.runtimeTtsNetworkCalls).toBe(0);
  });

  it("carries EXACTLY the keys tests/gauntlet/rubric.mjs reads", () => {
    expect(Object.keys(evidenceData).sort()).toEqual(
      [
        "ambientBeds",
        "crossfade",
        "duckDb",
        "musicLayers",
        "noConsecutiveRepeat",
        "runtimeTtsNetworkCalls",
        "sfxVariants",
        "voiceTransport",
      ].sort(),
    );
  });

  it("is reproducible: a second run of the same graph reports the same thing", () => {
    const again = buildAudioEvidence(fakeVoiceEnvironment().env, {
      rotationsPerEvent: 300,
      staticNetworkReferences: staticNetworkReferences(),
    });
    expect(again).toEqual(evidenceData);
  });

  it("the fetch probe really does count, so the zero means something", () => {
    const probe = countingFetchProbe();
    expect(probe.calls).toBe(0);
    probe("https://example.invalid/tts", { method: "POST" });
    probe();
    expect(probe.calls).toBe(2);
  });

  it("reports zero TTS calls even when no probe was injected at all", () => {
    const { speech, scheduler } = fakeVoiceEnvironment();
    const withoutProbe = buildAudioEvidence(
      { speech, platform: "mac", lang: "en-US", schedule: scheduler.schedule },
      { rotationsPerEvent: 12 },
    );
    expect(withoutProbe.runtimeTtsNetworkCalls).toBe(0);
    expect(withoutProbe.voiceTransport).toBe("webspeech");
  });

  it("counts a network reference if one is ever added to the audio source", () => {
    // The zero is load-bearing, so prove it can be non-zero.
    const poisoned = buildAudioEvidence(fakeVoiceEnvironment().env, {
      rotationsPerEvent: 12,
      staticNetworkReferences: 3,
    });
    expect(poisoned.runtimeTtsNetworkCalls).toBe(3);
  });
});

describe("D85: the artifact is written and turns the audio rubric green", () => {
  it("writes gauntlet/evidence/audio-graph.json", () => {
    if (!existsSync(EVIDENCE_DIR)) mkdirSync(EVIDENCE_DIR, { recursive: true });
    writeFileSync(join(EVIDENCE_DIR, ARTIFACT), `${JSON.stringify(evidenceData, null, 2)}\n`, "utf8");
    expect(existsSync(join(EVIDENCE_DIR, ARTIFACT))).toBe(true);
    const roundTripped = JSON.parse(readFileSync(join(EVIDENCE_DIR, ARTIFACT), "utf8"));
    expect(roundTripped).toEqual(evidenceData);
  });

  it("A-21.1 .. A-21.5: every audio rubric item passes against the written file", async () => {
    // The real rubric functions, not a copy of their thresholds.
    const audioItems = RUBRIC.filter((item) => item.kind === "audio");
    expect(audioItems.map((i) => i.id)).toEqual(["A-21.1", "A-21.2", "A-21.3", "A-21.4", "A-21.5"]);

    const evidencePort = {
      has: (name: string) => existsSync(join(EVIDENCE_DIR, name)),
      path: (name: string) => `gauntlet/evidence/${name}`,
      read: (name: string) => JSON.parse(readFileSync(join(EVIDENCE_DIR, name), "utf8")),
      assertNumber(name: string, key: string, predicate: (v: number) => boolean, what: string) {
        const value = this.read(name)[key];
        if (typeof value !== "number" || Number.isNaN(value)) {
          return { status: "fail", detail: `${name} has no numeric "${key}"` };
        }
        return { status: predicate(value) ? "pass" : "fail", detail: `${what}: ${key} = ${value}` };
      },
      assertShape(name: string, predicate: (d: unknown) => boolean, what: string) {
        return { status: predicate(this.read(name)) ? "pass" : "fail", detail: what };
      },
    };

    for (const item of audioItems) {
      const result = await item.run({ repo: REPO, evidence: evidencePort });
      expect(`${item.id}: ${result.status} - ${result.detail}`).toBe(
        `${item.id}: pass - ${result.detail}`,
      );
    }
  });
});
