import { describe, expect, it } from "vitest";
import {
  type TileOp,
  FALLBACK_RADII,
  VEIL_BY_STOP,
  accentTile,
  canyonTile,
  driftTile,
  dustTile,
  massifPoints,
  massifTile,
  moteTile,
  planeMaterialColor,
  ridgePoints,
  spirePoints,
  starTile,
  translateOps,
  veilFor,
  veilTile,
  wrapXY,
  wrapY,
} from "../../../src/game/render/tiles.js";
import {
  PALETTE_STOP_IDS,
  lightness,
  paletteFor,
  skyStops,
} from "../../../src/game/render/palette.js";

/**
 * THE WRAP SEAM.
 *
 * A player looked at the Title screen and said: "it's not a continuous seamless
 * loop. It has a real jolt to it, like it's reached the end and then it
 * restarts."
 *
 * The cause was not the wrap arithmetic, which was correct - `mod(offsetY, H)`
 * with content drawn at `y` and at `y - H`. It was that the two copies were
 * generated by two passes of a loop that called `rand()` INSIDE it, so the tile
 * at `dy = 0` and the tile at `dy = -h` were different landscapes and a whole
 * new arrangement snapped into frame at the seam. Every generator in the file
 * had the same shape and therefore the same bug.
 *
 * This file is the only thing that stops it coming back. The property is stated
 * once and checked against every generator by table, so a generator added later
 * is checked by the same assertion the day someone adds it to the list - and
 * `wrapY` is the only way to build a wrapping plane, so there is no third path
 * that could quietly re-roll a copy.
 */

const SEED = 0x1a17e;

/** mulberry32, identical to the one `parallax.ts` seeds its content with. */
function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const W = 1920;
const H = 1080;

const MARS = paletteFor("mars");
const MATERIALS = [
  {
    radii: FALLBACK_RADII,
    facets: [{ x: 0.2, y: 0.1, r: 0.22 }],
    fill: "#7A2E17",
    facet: "#4A1F12",
    rim: "#B5522A",
  },
];

/**
 * Every generator that produces WRAPPING content, with a fresh seed each time.
 * Adding a generator to `tiles.ts` without adding it here is the one gap left,
 * so the list is deliberately exhaustive and named after the module's exports.
 */
const GENERATORS: readonly { name: string; build: (rand: () => number) => TileOp[] }[] = [
  {
    name: "massifTile (far: ridge, no rim, no dots)",
    build: (rand) =>
      massifTile(W, H, {
        fill: "#A0846F",
        rimColor: "#B49A88",
        alpha: 0.95,
        light: -2,
        rand,
        count: 2,
        scale: 0.72,
        rim: false,
        dots: false,
        ridgeAt: 0.62,
        avoid: { x: 500, r: 190 },
      }),
  },
  {
    name: "massifTile (mid: rim + dots + spires)",
    build: (rand) =>
      massifTile(W, H, {
        fill: "#875F4E",
        rimColor: "#A0796A",
        alpha: 1,
        light: -2,
        rand,
        count: 2,
        scale: 0.95,
        rim: true,
        dots: true,
        ridgeAt: 0.34,
        avoid: null,
      }),
  },
  {
    name: "canyonTile",
    build: (rand) =>
      canyonTile(W, H, { fill: "#39140B", rimColor: "#5A3126", light: -2, rand }),
  },
  { name: "dustTile", build: (rand) => dustTile(W, H, "#C0A28C", rand) },
  { name: "starTile", build: (rand) => starTile(W, H, "#F7E6D0", 90, rand) },
  { name: "moteTile", build: (rand) => moteTile(W, H, "#39140B", "#FF6B4A", rand) },
  { name: "accentTile", build: (rand) => accentTile(W, H, "#FF8F74", rand) },
  {
    name: "driftTile (open lane)",
    build: (rand) =>
      driftTile(W, H, {
        materials: MATERIALS,
        count: 7,
        minPx: 10,
        maxPx: 26,
        alpha: 0.9,
        light: -2,
        laneGuard: 0,
        rand,
      }),
  },
  {
    name: "driftTile (lane-guarded)",
    build: (rand) =>
      driftTile(W, H, {
        materials: MATERIALS,
        count: 4,
        minPx: 70,
        maxPx: 132,
        alpha: 1,
        light: -2,
        laneGuard: 0.26,
        rand,
      }),
  },
  {
    name: "veilTile",
    build: (rand) =>
      veilTile(W, H, {
        spec: veilFor("mars") as NonNullable<ReturnType<typeof veilFor>>,
        tint: "#FBEEDC",
        laneGuard: 0.26,
        rand,
      }),
  },
];

/** Every coordinate in an op, flattened, so two ops can be compared as numbers. */
function coords(op: TileOp): number[] {
  if (op.kind === "poly") return op.points.flatMap((p) => [p.x, p.y]);
  return [op.x, op.y];
}

/** Everything about an op that is NOT its position. */
function style(op: TileOp): string {
  switch (op.kind) {
    case "poly":
      return `poly|${op.color}|${op.alpha}|${op.points.length}`;
    case "circle":
      return `circle|${op.color}|${op.alpha}|${op.r}`;
    case "ellipse":
      return `ellipse|${op.color}|${op.alpha}|${op.w}|${op.h}`;
    default:
      return `sprite|${op.tex}|${op.color}|${op.alpha}|${op.size}|${op.additive}`;
  }
}

describe("the wrap seam: the two copies of a tile are the SAME content", () => {
  for (const gen of GENERATORS) {
    it(`${gen.name}: the copy at dy = -h is the tile at dy = 0, offset by h and nothing else`, () => {
      const tile = gen.build(rng(SEED));
      expect(tile.length, "generator produced no geometry to compare").toBeGreaterThan(0);

      const wrapped = wrapY(tile, H);
      expect(wrapped).toHaveLength(tile.length * 2);
      const first = wrapped.slice(0, tile.length);
      const second = wrapped.slice(tile.length);

      for (let i = 0; i < first.length; i++) {
        const a = first[i] as TileOp;
        const b = second[i] as TileOp;
        // Same shape, same colour, same alpha, same size...
        expect(style(b), `op ${i} style`).toBe(style(a));
        const ca = coords(a);
        const cb = coords(b);
        expect(cb, `op ${i} coordinate count`).toHaveLength(ca.length);
        // ...and every coordinate differs by exactly (0, -h).
        for (let k = 0; k < ca.length; k += 2) {
          expect(cb[k], `op ${i} x[${k}]`).toBe(ca[k]);
          expect(cb[k + 1], `op ${i} y[${k}]`).toBe((ca[k + 1] as number) - H);
        }
      }
    });

    it(`${gen.name}: is deterministic, so a seeded frame is the same frame`, () => {
      // If a generator reached for Math.random the seam test above would still
      // pass (both copies come from one tile) and a pixel-diff evidence test
      // would go flaky instead. Cheap to rule out here.
      expect(gen.build(rng(SEED))).toEqual(gen.build(rng(SEED)));
    });
  }

  it("the old bug reproduces: re-rolling per copy is NOT a translation", () => {
    // The guard that makes this suite mean something. If `massifTile` were ever
    // rewritten to generate each copy from a live rand() again, the two tiles
    // would differ - this asserts that such a difference is actually detectable
    // by the comparison above, rather than the comparison being vacuous.
    const rand = rng(SEED);
    const build = (): TileOp[] =>
      massifTile(W, H, {
        fill: "#875F4E",
        rimColor: "#A0796A",
        alpha: 1,
        light: -2,
        rand,
        count: 2,
        scale: 0.95,
        rim: true,
        dots: true,
        ridgeAt: 0.34,
        avoid: null,
      });
    const a = build();
    const b = translateOps(build(), 0, -H);
    expect(JSON.stringify(a)).not.toBe(JSON.stringify(translateOps(b, 0, H)));
  });

  it("wraps on BOTH axes for the planes that also drift sideways", () => {
    const tile = driftTile(W, H, {
      materials: MATERIALS,
      count: 5,
      minPx: 20,
      maxPx: 40,
      alpha: 1,
      light: -2,
      laneGuard: 0,
      rand: rng(SEED),
    });
    const wrapped = wrapXY(tile, W, H);
    // Four copies: (0,0), (-w,0), (0,-h), (-w,-h). A plane that drifts sideways
    // has a seam on x as well, and it fails exactly the same way.
    expect(wrapped).toHaveLength(tile.length * 4);
    const offsets = [
      [0, 0],
      [-W, 0],
      [0, -H],
      [-W, -H],
    ];
    const base = coords(tile[0] as TileOp);
    for (const [i, [dx, dy]] of offsets.entries()) {
      const got = coords(wrapped[i * tile.length] as TileOp);
      expect(got[0], `copy ${i} x`).toBe((base[0] as number) + (dx as number));
      expect(got[1], `copy ${i} y`).toBe((base[1] as number) + (dy as number));
    }
  });
});

describe("silhouette character (WORLD-BAR item 5, judge note 4 and 5)", () => {
  it("every silhouette plane carries a CONTINUOUS edge across the whole frame", () => {
    // Judge note 4: "the masses read as slabs floating in soup, not landforms at
    // distances." A plane whose widest shape is narrower than the stage is a
    // collection of rectangles; one unbroken edge past both margins is terrain.
    const ridge = ridgePoints(W, 600, 40, 120, 9, rng(SEED));
    const xs = ridge.map((p) => p.x);
    expect(Math.min(...xs)).toBeLessThan(0);
    expect(Math.max(...xs)).toBeGreaterThan(W);
    // ...and it is a STEPPED edge, not a straight line.
    const ys = new Set(ridge.map((p) => Math.round(p.y)));
    expect(ys.size).toBeGreaterThan(6);
  });

  it("a massif is angular: no two consecutive edges are collinear", () => {
    const pts = massifPoints(500, 500, 200, 300, rng(SEED));
    expect(pts.length).toBeGreaterThanOrEqual(10);
    const corners = pts.filter((p, i) => {
      const a = pts[(i + pts.length - 1) % pts.length] as { x: number; y: number };
      const b = pts[(i + 1) % pts.length] as { x: number; y: number };
      const cross = (p.x - a.x) * (b.y - p.y) - (p.y - a.y) * (b.x - p.x);
      return Math.abs(cross) > 1;
    });
    expect(corners.length, "a rounded rectangle has four").toBeGreaterThan(6);
  });

  it("a spire tapers to a point above its base", () => {
    const s = spirePoints(100, 500, 20, 160);
    const top = s.reduce((m, p) => (p.y < m.y ? p : m), s[0] as { x: number; y: number });
    expect(top.y).toBe(500 - 160);
    expect(Math.max(...s.map((p) => p.x)) - Math.min(...s.map((p) => p.x))).toBe(40);
  });
});

describe("decorative debris is not in the ship's lane (AC-22.8, FR-8/D19)", () => {
  it("lane-guarded planes leave the centre of the frame completely clear", () => {
    // Word plates fall down the middle and legibility is the game. Anything on a
    // plane in front of them that strays into the centre column is a defect, not
    // atmosphere - so the guard is asserted, not trusted.
    const guard = 0.26;
    const ops = driftTile(W, H, {
      materials: MATERIALS,
      count: 40,
      minPx: 70,
      maxPx: 132,
      alpha: 1,
      light: -2,
      laneGuard: guard,
      rand: rng(SEED),
    });
    for (const op of ops) {
      const xs = op.kind === "poly" ? op.points.map((p) => p.x) : [op.x];
      for (const x of xs) {
        const inCentre = x > W * guard && x < W * (1 - guard);
        expect(inCentre, `x=${x.toFixed(0)} is inside the word lane`).toBe(false);
      }
    }
  });

  it("the veil keeps out of the lane too", () => {
    for (const id of PALETTE_STOP_IDS) {
      const spec = veilFor(id);
      if (spec === null) continue;
      const ops = veilTile(W, H, { spec, tint: "#FFFFFF", laneGuard: 0.26, rand: rng(SEED) });
      for (const op of ops) {
        expect(op.kind).toBe("ellipse");
        if (op.kind !== "ellipse") continue;
        // The band's CENTRE stays in the outer quarter; its soft width may reach
        // inward, which is what makes it read as air rather than as a bar.
        const inCentre = op.x > W * 0.45 && op.x < W * 0.55;
        expect(inCentre, `${id} veil band at x=${op.x.toFixed(0)}`).toBe(false);
      }
    }
  });

  it("the veil is thin and low-alpha, because legibility is the game", () => {
    for (const id of PALETTE_STOP_IDS) {
      const spec = veilFor(id);
      if (spec === null) continue;
      const ops = veilTile(W, H, { spec, tint: "#FFFFFF", laneGuard: 0.26, rand: rng(SEED) });
      for (const op of ops) {
        // Before the layer's own 0.72 master alpha. Nothing a word could ever
        // sit behind exceeds 16% on its own.
        expect(op.alpha, `${id} veil band alpha`).toBeLessThanOrEqual(0.17);
        if (op.kind === "ellipse") {
          expect(op.h, `${id} veil band height`).toBeLessThan(120);
        }
      }
    }
  });

  it("a decorative rock takes its plane's value, never a value between planes", () => {
    // The point of `planeMaterialColor`: the same rock at four distances, each
    // belonging to the plane it is on. If a near rock landed halfway between the
    // near and mid plane it would read as a fifth, broken layer.
    const sky = skyStops(MARS)[1];
    const far = planeMaterialColor("#B5522A", sky, "#AD8E78", 0.9, 0.55);
    const near = planeMaterialColor("#B5522A", sky, "#39140B", 0, 0.8);
    expect(lightness(far)).toBeGreaterThan(lightness(near) + 20);
    expect(Math.abs(lightness(far) - lightness("#AD8E78"))).toBeLessThan(14);
    expect(Math.abs(lightness(near) - lightness("#39140B"))).toBeLessThan(14);
  });
});

describe("the foreground veil is sourced, not invented (PRD section 6 / FR-12b)", () => {
  it("every stop that has a veil names what it is and cites where that comes from", () => {
    for (const id of PALETTE_STOP_IDS) {
      const spec = VEIL_BY_STOP[id];
      if (spec === null || spec === undefined) continue;
      expect(spec.what.length, `${id} says what the veil is`).toBeGreaterThan(8);
      expect(spec.source.length, `${id} cites a source`).toBeGreaterThan(8);
    }
  });

  it("the two stops that need no invention at all are real weather", () => {
    // Neptune has photographed methane ice clouds; New Horizons found roughly
    // twenty stacked haze layers at Pluto. Those two are the reason this is a
    // sourced feature rather than "clouds in space".
    expect(veilFor("neptune")?.kind).toBe("cloud");
    expect(veilFor("pluto")?.kind).toBe("haze");
  });

  it("every stop with a NASA claim cites a science.nasa.gov page", () => {
    for (const id of PALETTE_STOP_IDS) {
      const spec = VEIL_BY_STOP[id];
      if (spec === null || spec === undefined) continue;
      // Earth is the exception and it is an honest one: D57 gives the launchpad
      // no belt, so FR-12b has no Earth row to cite. Its claim is about our own
      // palette, and it cites the palette.
      if (id === "earth") {
        expect(spec.source).toContain("palettes.json");
        continue;
      }
      expect(spec.source, `${id}`).toMatch(/^https:\/\/science\.nasa\.gov\//);
    }
  });
});
